#!/usr/bin/env bash
#
# 9Router native systemd worker topology — pure validation + derivation.
# ============================================================================
#
# Sourced by scripts/install.sh (never executed on its own during a run):
#
#   . "$REPO_DIR/scripts/systemd-worker-topology.sh"
#   worker_env_prepare 20127 "$API_WORKERS"     # -> prints count, sets WORKER_* vars
#   worker_env_write    <dir> "$API_WORKERS"    # -> writes per-instance env files
#   worker_stale_units  "$SYSTEMD_UNIT_DIR" "$API_WORKERS"
#   worker_runtime_envs "$WORKER_ENV_DIR" "$API_WORKERS"
#
# Deliberate design notes (both are load-bearing, not style):
#   • systemd `Environment=` performs NO shell expansion, so a worker unit can
#     never do arithmetic. Every derived value (port, role, URL list) is
#     precomputed by the installer into a per-instance EnvironmentFile.
#   • EnvironmentFile entries are applied in order: the later private file
#     overrides WORKER_ROLE=control and the shared control port safely.
#
# API_WORKERS counts TOTAL Node processes, matching Docker: the control process
# plus API_WORKERS-1 API workers, on BACKEND_PORT+3+i for i=1..N-1.

# Keep identical to MAX_API_WORKERS in custom-server.js and the Docker entrypoint.
WORKER_MAX=8

# The MySQL protocol is not a 9Router backend. Guarding on "does the URL look
# like postgres" instead of a DB_TYPE allow-list means an unknown DB_TYPE can
# never silently disable the SQLite guard below.
DB_URL_UNSUPPORTED_RE='^(mysql|mariadb|sqlite|sqlite3|file|mongodb|redis|libsql|d1):'

worker_topology_error() { printf '%s\n' "$*" >&2; return 1; }

worker_env_write() { # worker_env_write <dir> <total-workers>
  local dir="$1" total="$2"
  mkdir -p "$dir"
  chmod 700 "$dir"
  local i stale instance
  for ((i = 1; i < total; i++)); do
    worker_env_write_one "$dir" "$BACKEND_PORT" "$total" "$i"
  done
  # A shrinking API_WORKERS must not leave an instance file behind for a worker
  # unit that is about to be disabled.
  local stale
  for stale in "$dir"/*.env; do
    [ -e "$stale" ] || continue
    instance="$(basename "$stale" .env)"
    case "$instance" in ''|*[!0-9]*) continue ;; esac
    [ "$instance" -lt "$total" ] || rm -f "$stale"
  done
}

worker_env_write_one() { # worker_env_write_one <dir> <backend-port> <total> <instance>
  local dir="$1" backend_port="$2" total="$3" instance="$4" file tmp
  case "$backend_port" in ''|*[!0-9]*) worker_topology_error "BACKEND_PORT must be a positive integer (got '$backend_port')"; return 1 ;; esac
  case "$total" in ''|*[!0-9]*|0*) worker_topology_error "API_WORKERS must be a positive integer (got '$total')"; return 1 ;; esac
  [ "$total" -le "$WORKER_MAX" ] || { worker_topology_error "API_WORKERS=$total exceeds the supported maximum of $WORKER_MAX"; return 1; }
  [ $((backend_port + 2 + total)) -le 65535 ] || { worker_topology_error "BACKEND_PORT=$backend_port + API_WORKERS=$total overflows the TCP port range"; return 1; }
  case "$instance" in ''|*[!0-9]*) worker_topology_error "worker instance must be numeric"; return 1 ;; esac
  [ "$instance" -ge 1 ] && [ "$instance" -lt "$total" ] || {
    worker_topology_error "worker instance $instance is outside 1..$((total - 1))"; return 1
  }
  mkdir -p "$dir" && chmod 700 "$dir" || return 1
  file="$dir/$instance.env"; tmp="$file.tmp.$$"
  {
    echo "# Generated by 9Router worker supervisor."
    echo "WORKER_ROLE=api"
    echo "NINEROUTER_WORKER_ROLE=api"
    echo "PORT=$((backend_port + 3 + instance))"
    echo "HOSTNAME=127.0.0.1"
    echo "API_WORKERS=$total"
  } > "$tmp" && chmod 600 "$tmp" && mv -f "$tmp" "$file"
}

worker_runtime_envs() { # worker_runtime_envs <dir> <total-workers>
  local dir="$1" total="$2" f i
  for ((i = 1; i < total; i++)); do
    f="$dir/$i.env"
    [ -f "$f" ] && printf '%s ' "$f"
  done
}

worker_stale_units() { # worker_stale_units <unit-dir> <total-workers>
  local unit_dir="$1" total="$2" f instance
  [ -d "$unit_dir" ] || return 0
  # `systemctl enable` on a template records an instance as a symlink under
  # 9router-workers.target.wants; explicit unit files only appear if the unit was
  # written directly. Both are scanned, and every other *.service is ignored so
  # an unrelated numeric name can never collide with the worker range.
  local wants="$unit_dir/${SERVICE_WORKERS_TARGET:-9router-workers.target}.wants"
  for f in "$unit_dir"/9router-worker@*.service "$wants"/9router-worker@*.service; do
    [ -e "$f" ] || continue
    instance="$(basename "$f" .service)"
    case "$instance" in 9router-worker@*) instance="${instance#9router-worker@}" ;; *) continue ;; esac
    case "$instance" in ''|*[!0-9]*) continue ;; esac
    if [ "$instance" -ge "$total" ]; then
      printf '%s %s\n' "$instance" "$f"
    fi
  done
}

if [ "${1:-}" = "write-one" ]; then
  shift
  worker_env_write_one "$@"
  exit $?
fi

# worker_env_prepare <backend-port> <total-workers>
# Validates the requested topology and prints the effective total Node process
# count. Returns non-zero (with a message on stderr) for any rejected request.
# On success WORKER_TOTAL is exported for callers that prefer a variable.
worker_env_prepare() {
  local backend_port="${1:-20127}" total="${2:+${2}}"

  case "$backend_port" in
    ''|*[!0-9]*) worker_topology_error "BACKEND_PORT must be a positive integer (got '$backend_port')"; return 1 ;;
  esac
  case "$total" in
    ''|*[!0-9]*|0*) worker_topology_error "API_WORKERS must be a positive integer (got '$total')"; return 1 ;;
  esac
  [ "$total" -le "$WORKER_MAX" ] || {
    worker_topology_error "API_WORKERS=$total exceeds the supported maximum of $WORKER_MAX total Node processes"
    return 1
  }
  # Port 65535 is the ceiling. The last instance is BACKEND_PORT+3+total-1.
  [ "$total" -eq 1 ] || [ $((backend_port + 2 + total)) -le 65535 ] || {
    worker_topology_error "BACKEND_PORT=$backend_port + API_WORKERS=$total overflows the TCP port range"
    return 1
  }

  local url selected_pg=0 other_url_set=0
  url="${DATABASE_URL:-}"
  case "$url" in
    postgres://*|postgresql://*) selected_pg=1 ;;
    "$DB_URL_UNSUPPORTED_RE"*) :
      # An unsupported URL scheme is a hard stop: it cannot be re-tested below.
      worker_topology_error "DATABASE_URL scheme is not supported. Use postgres://user:pass@host:5432/9router or unset DATABASE_URL for SQLite."
      return 1 ;;
    '') : ;;
    *) other_url_set=1 ;;
  esac
  if [ "$other_url_set" = 1 ]; then
    worker_topology_error "DATABASE_URL is set but is not a postgres:// URL. DB_TYPE=postgres cannot override it, so multi-worker mode was refused."
    return 1
  fi

  # API workers share one control plane: per-process SQLite would hand every
  # worker its own database file.
  if [ "$total" -gt 1 ] && [ "$selected_pg" != 1 ] &&
     [ "$(printf '%s' "${DB_TYPE:-}" | tr '[:upper:]' '[:lower:]')" != "postgres" ]; then
    worker_topology_error "API_WORKERS>1 requires PostgreSQL. Set DATABASE_URL=postgres://user:pass@host:5432/9router (or DB_TYPE=postgres), or keep API_WORKERS=1 for the SQLite default."
    return 1
  fi

  # Refuse to invoke a role that starts Node (and its bootstrap migrations) just
  # to discover the config is invalid.
  local noexec="${NOEXEC:-0}"
  if [ "$noexec" != 1 ] && [ -x "${NODE_BIN:-/usr/bin/env}" ] &&
     [ -f "${RELEASE_DIR:-}/custom-server.js" ]; then
    if ! ( cd "${RELEASE_DIR}" && WORKER_ROLE=control API_WORKERS="$total" DATABASE_URL="${DATABASE_URL:-}" \
             DB_TYPE="${DB_TYPE:-}" "${NODE_BIN:-env}" node custom-server.js --check-config >/dev/null 2>&1 ); then
      worker_topology_error "Rejected by custom-server.js --check-config: WORKER_ROLE=control API_WORKERS=$total DATABASE_URL/DB_TYPE did not validate."
      return 1
    fi
  fi

  WORKER_TOTAL="$total"
  printf '%s\n' "$total"
  return 0
}
